### ISSUE TITLE
Using it on Angular5

### ISSUE THREAD

**Issue by jacopoRufini** [KonstantinKai/medium-editor-colorpicker-buttons#1]
Hi, is it possible to implement this in medium-angular-directive?

**Comment by KonstantinKai** [comment]
@jacopoRufini, Hi, I'm not familiar with Angular, but I think this can works
```

**Comment by KonstantinKai** [comment]
@jacopoRufini, Hi, I'm not familiar with Angular, but I think this can works because `MediumEditor` constructor can accept real nodes and string selectors (the directive code I took from angular official site https://angular.io/guide/attribute-directives )
```js
import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[appHighlight]'
})
export class HighlightDirective {
    constructor(el: ElementRef) {
      new MediumEditor(el, {
	toolbar: {
		buttons: ['bold', 'italic', 'underline', 'anchor', 'h2', 'h3', 'textcolor']
	},
        // ...rest config
      })
    }
}
```
